-- SMC Trade production schema
-- Run this in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  free_daily_used integer not null default 0,
  free_daily_date date not null default current_date,
  paid_credits bigint not null default 0,
  unlimited_until timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.analyses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null,
  timeframe text not null,
  result jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.credit_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount bigint not null,
  reason text not null,
  external_id text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.analyses enable row level security;
alter table public.credit_ledger enable row level security;

drop policy if exists "users read own profile" on public.profiles;
create policy "users read own profile" on public.profiles for select using (auth.uid() = id);

drop policy if exists "users read own analyses" on public.analyses;
create policy "users read own analyses" on public.analyses for select using (auth.uid() = user_id);

create or replace function public.ensure_profile(p_user_id uuid)
returns void language plpgsql security definer as $$
begin
  insert into public.profiles(id,email) values(p_user_id,(select email from auth.users where id=p_user_id))
  on conflict(id) do nothing;
end $$;

create or replace function public.get_user_credits(p_user_id uuid)
returns json language plpgsql security definer as $$
declare p public.profiles%rowtype; free_limit integer := coalesce(nullif(current_setting('app.free_daily_analyses', true), '')::integer, 6);
begin
  perform public.ensure_profile(p_user_id);
  select * into p from public.profiles where id=p_user_id;
  if p.free_daily_date <> current_date then
    update public.profiles set free_daily_used=0,free_daily_date=current_date where id=p_user_id;
    p.free_daily_used := 0;
  end if;
  return json_build_object('remaining', case when p.unlimited_until > now() then 999999999 else greatest(0,free_limit-p.free_daily_used)+p.paid_credits end,
                          'free_remaining', case when p.unlimited_until > now() then 999999999 else greatest(0,free_limit-p.free_daily_used) end,
                          'paid_credits', p.paid_credits,
                          'unlimited', p.unlimited_until > now());
end $$;

create or replace function public.consume_analysis_credit(p_user_id uuid)
returns json language plpgsql security definer as $$
declare p public.profiles%rowtype; free_limit integer := 6;
begin
  perform public.ensure_profile(p_user_id);
  select * into p from public.profiles where id=p_user_id for update;

  if p.free_daily_date <> current_date then
    update public.profiles set free_daily_used=0,free_daily_date=current_date where id=p_user_id;
    p.free_daily_used := 0;
    p.free_daily_date := current_date;
  end if;

  if p.unlimited_until is not null and p.unlimited_until > now() then
    return json_build_object('allowed',true,'remaining',999999999);
  end if;

  if p.free_daily_used < free_limit then
    update public.profiles set free_daily_used=free_daily_used+1 where id=p_user_id;
  elsif p.paid_credits > 0 then
    update public.profiles set paid_credits=paid_credits-1 where id=p_user_id;
  else
    return json_build_object('allowed',false,'remaining',0);
  end if;

  return (select json_build_object('allowed',true,'remaining',(get_user_credits(p_user_id)->>'remaining')::bigint));
end $$;

create or replace function public.grant_credits(p_user_id uuid,p_amount bigint,p_reason text,p_external_id text)
returns void language plpgsql security definer as $$
begin
  insert into public.credit_ledger(user_id,amount,reason,external_id) values(p_user_id,p_amount,p_reason,p_external_id);
  update public.profiles set paid_credits=paid_credits+p_amount where id=p_user_id;
end $$;

create or replace function public.grant_unlimited(p_user_id uuid,p_until timestamptz,p_reason text,p_external_id text)
returns void language plpgsql security definer as $$
begin
  update public.profiles set unlimited_until=p_until where id=p_user_id;
  insert into public.credit_ledger(user_id,amount,reason,external_id) values(p_user_id,0,p_reason,p_external_id);
end $$;

-- Create profile automatically for new users.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer as $$
begin
  insert into public.profiles(id,email) values(new.id,new.email) on conflict(id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();
